# -*- coding: utf-8 -*-
"""IPYNB_to_a_PDF_CONVERTOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yLFcHzQXWbpaOC7_Fqf7oR06PCDVWyfw

# **nbconvert**

**The `nbconvert` tool allows you to convert a Jupyter `.ipynb` notebook file into another static format such as: HTML, LaTeX, PDF, Markdown and more.**
"""

from google.colab import drive
drive.mount('/content/drive')

"""/content/kNN.ipynb

<sup>Source: [Convert Notebooks to other formats](https://nbconvert.readthedocs.io/en/latest/) from nbconvert Documentation</sup>

## **Method I - Convert notebook to HTML then print as PDF**
"""

!jupyter nbconvert --to html "/content/drive/MyDrive/Colab Notebooks/Linear_regression.ipynb"

"""## **Method II - Convert notebook directly as a PDF**"""

!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic

!sudo apt-get install pandoc

!jupyter nbconvert --to pdf "/content/drive/MyDrive/Colab Notebooks/Linear_regression.ipynb"

"""# **References and Additional Learning**

## **Websites**

- **[Convert Notebooks to other formats](https://nbconvert.readthedocs.io/en/latest/) from nbconvert Documentation**

- **[Installing TeX](https://nbconvert.readthedocs.io/en/latest/install.html#installing-tex) from nbconvert Documentation**

# **Connect**
- **Feel free to connect with Adrian on [YouTube](https://www.youtube.com/channel/UCPuDxI3xb_ryUUMfkm0jsRA), [LinkedIn](https://www.linkedin.com/in/adrian-dolinay-frm-96a289106/), [Twitter](https://twitter.com/DolinayG), [GitHub](https://github.com/ad17171717), [Medium](https://adriandolinay.medium.com/) and [Odysee](https://odysee.com/@adriandolinay:0). Happy coding!**
"""